### ISSUE TITLE
Spacing at Publication section

### ISSUE THREAD

**Issue by albert-ying** [joelnitta/joelnitta-cv#1]
Hi Joel, thank you for sharing this. I encountered a minor issue, which is also shown in your example file: the spacing between the "Publication" section name and the first reference is too narrow. I tried to add an empty line, but then it would be too wide. I'm wondering if there is any way to fix it so it looks consistent with other sections. Thank you!

**Comment by joelnitta** [comment]
Thanks @albert-ying for the issue! I noticed the same thing, but didn't feel like sinking a bunch of time into latex to fix it ATM... I will have another look...
